name: Keep Render alive

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping backend
        run: |
          STATUS=$(curl --silent --output /dev/null \
          --write-out "%{http_code}" \
          https://my-website-g7nn.onrender.com)

          echo "Status: $STATUS"

          if [ "$STATUS" -ne 200 ]; then
            echo "Failed"
            exit 1
          fi